FROM python:3.7

# update modules
RUN apt-get -y update \
    && apt-get -y upgrade

WORKDIR /var/www/html

# install packages
#ADD requirements.txt /var/www/html
#RUN pip install -r requirements.txt
